sudo: false
language: cpp
cache:
 ccache: true
 directories:
    - /home/travis/toolchain

matrix:
  include:

  # Ubuntu, g++-8
  - os: linux
    dist: trusty
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
          - libboost1.55-all-dev
          - libssl-dev
          - g++-8
          - gcc-8
    env:
    - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - LABEL="linux"
    - _DEPLOYABLE="true"
    - STRIP="strip"

  # Ubuntu, g++-7
  - os: linux
    dist: trusty
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
          - libboost1.55-all-dev
          - libssl-dev
          - g++-7
          - gcc-7
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - LABEL="linux-g++-7"
    - STRIP="strip"

  # Ubuntu, clang-6
  - os: linux
    dist: trusty
    compiler: clang
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-6.0
        packages:
          - libboost1.55-all-dev
          - libssl-dev
          - clang-6.0
          - libstdc++-7-dev
    env:
    - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
    - LABEL="linux-clang-6"
    - STRIP="strip"

  # Arm (aarch64) cross compile
  - os: linux
    dist: trusty
    env:
    - MATRIX_EVAL="CC=aarch64-linux-gnu-gcc && CXX=aarch64-linux-gnu-g++"
    - LABEL="aarch64"
    - _DEPLOYABLE="true"
    - STRIP="aarch64-linux-gnu-strip"

before_install:
- eval $MATRIX_EVAL

script:
- eval $MATRIX_EVAL
# If we're cross compiling aarch64, make sure our build enivornment is setup
# we do this in the script stage because this happens after the repo is cloned
- if [[ "$LABEL" == "aarch64" ]]; then source scripts/prep-aarch64.sh ; fi
- mkdir build && cd build
- cmake -DARCH=default -DCMAKE_BUILD_TYPE=Release -DSTATIC=true ..
- make -j2
- if [[ "$LABEL" != "aarch64" ]]; then ./src/cryptotest ; fi

before_deploy:
- if [[ "${TRAVIS_TAG}" == "" ]]; then export TRAVIS_TAG=${TRAVIS_COMMIT} ; fi
- cd src
- TARGETS="Bitcoinnovad miner zedwallet Bitcoinnova-service zedwallet-beta cryptotest wallet-api"
- ${STRIP} ${TARGETS}
- rm -rf bitcoinnova-${TRAVIS_TAG}
- mkdir bitcoinnova-${TRAVIS_TAG}
- cp ${TARGETS} bitcoinnova-${TRAVIS_TAG}/
- cp ../../LICENSE bitcoinnova-${TRAVIS_TAG}/
- tar cvfz bitcoinnova-${TRAVIS_TAG}-${LABEL}.tar.gz bitcoinnova-${TRAVIS_TAG}/
- rm -rf builds
- mkdir builds
- cp bitcoinnova-${TRAVIS_TAG}-${LABEL}.tar.gz builds
- cd builds

deploy:
  - provider: releases
    api_key:
      secure: X39CcZqsQAFwm9gbDzNgPfr4kZZJ61MWvWQ2ks3ubKdENH8G0vWi+bOtC1DPwxofS+zovg10n7UIYBF1BrPrHW/nYTIseAJdemWBAiakuR+10HxN+m6B3DLrC11gntD0VgR2ezshqs80Vhfhf6UwnJOBdSgd9XsBTRw+PQIeDijfCsPgRHMDwNTr6+fsIysR/8cEVvkpCY71U+ZFVJq3AsDZMlqx6etiM+HW8b9k9Qbr3WjhfWbBvve917YnhoFSWb2YphGTHUZJ1xbBMcbdk96H/5IiV3lUjkpj6QCBWD9waTC5Rr03D0lc4FoGgFvvfLQ+mkMLbTp966DwdodC87PtlnIsZdAus9Mmso+QWIPc7GlX5rO/R+dLV2lTHFl7FzvUkurzEvLBcj5Pwsk9PEkPbWk3VomORazdAA5NJd6vk5plUaQFR/c39YDcynum9cbfe0/ODSmqBx9go35dITmHKIJmdupc8oJ/a2L+eqdlsL9/c0SE7yz7adIWa2ChHYRIwLQ4qQ2toBO+uq5UTlpldVkPLyAFSp0WpO6kVs/qL8raeyBeAkHu0WQ2nPXPSIc0qkdekdYebvigA3GoemXI9xB5P0fiHqvdr2860QsZAvEDcbKPP0pDDQodngb0FuZaZ0M+G+mNDCsCa8xG86118/qjQGxCzgyu5fXSER8=
    file:
      - bitcoinnova-${TRAVIS_TAG}-${LABEL}.tar.gz
    skip_cleanup: true
    on:
      repo: IB313184/Bitcoinnova-0.18.1
      tags: true
      condition: "$_DEPLOYABLE = true"
